### ISSUE TITLE
Add Score to SearchAsync Results

### ISSUE THREAD

**Issue by VibeNL** [jabacrack/YahooFinanceApiNext#11]
Would you consider adding the 'score' value to the search function results 👼 :

YahooFinanceApi/Yahoo - Search.cs

**Comment by jabacrack** [comment]
No problem, but what exactly does this parameter mean?

**Comment by VibeNL** [comment]
I would assume the score on the match, so the higher the better 👼

**Comment by jabacrack** [comment]
Looks like the truth. By the way, it looks like the search results are already sorted by points (by Yahoo).

**Comment by VibeNL** [comment]
Great, thank you!

**Comment by VibeNL** [comment]
@jabacrack  Can it be that you haven't updated the NuGet package 👼 ?

**Comment by jabacrack** [comment]
> @jabacrack Can it be that you haven't updated the NuGet package 👼 ?

Done
